### ISSUE TITLE
书里是这么写的，但是我不是很明白，读的代码加了同步的目的是什么，方便指导一下吗

### ISSUE THREAD

**Issue by munan56** [Huazie/FleaJavaConcurrency#1]
https://github.com/Huazie/FleaJavaConcurrency/blob/f1bf2e8a34347ed34f5c2c07db847e95835e61de/thread-safety-demo/src/main/java/com/huazie/flea/concurrency/threadsafety/demo6/CachedFactorizer.java#L36

**Comment by munan56** [comment]
我看到了第三章。。

**Comment by huazie** [comment]
> https://github.com/Huazie/FleaJavaConcurrency/blob/f1bf2e8a34347ed34f5c2c07db847e95835e61de/thread-safety-demo/src/main/java/com/huazie/flea/concurrency/threadsafety/demo6/CachedFactorizer.java#L36

hits变量 也在doGet的同步代码块中， 要保证 hits变量的访问也是线程安全的， 就需要synchronized 字段，因为不加这个，在其他线程doGet的时候，hits可能发生变化，别的线程getHits获取的就是失效的值，这样可以理解嘛？

**Comment by munan56** [comment]
> > https://github.com/Huazie/FleaJavaConcurrency/blob/f1bf2e8a34347ed34f5c2c07db847e95835e61de/thread-safety-demo/src/main/java/com/huazie/flea/concurrency/threadsafety/demo6/CachedFactorizer.java#L36
> 
> hits变量 也在doGet的同步代码块中， 要保证 hits变量的访问也是线程安全的， 就需要synchronized 字段，因为不加这个，在其他线程doGet的时候，hits可能发生变化，别的线程getHits获取的就是失效的值，这样可以理解嘛？

是这么个意思，感谢
